<?php

use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'first_name' => 'Гаврила',
                'last_name' => 'Ерофеев',
                'email' => 'ErofeevGavrila@gmail.com',
                'password' => bcrypt('KP4bsmMpJxon'),
                'role' => 'admin',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375292425592',
                'avatar' => 'myAvatar1.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Элина',
                'last_name' => 'Быкова',
                'email' => 'ByikovaElina391@gmail.com',
                'password' => bcrypt('fe3DQZe1tQrO'),
                'role' => 'doctor',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375298701513',
                'avatar' => 'myAvatar2.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Станислава',
                'last_name' => 'Ушакова',
                'email' => 'UshakovaStanislava248@gmail.com',
                'password' => bcrypt('5LHcrwRHe1PM'),
                'role' => 'doctor',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375293461761',
                'avatar' => 'myAvatar3.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Владилена',
                'last_name' => 'Савельева',
                'email' => 'SavelevaVladilena119@gmail.com',
                'password' => bcrypt('rCBLojkauuAd'),
                'role' => 'doctor',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375296352932',
                'avatar' => 'myAvatar4.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Зосима',
                'last_name' => 'Мамедов',
                'email' => 'MamedovZosima143@gmail.com',
                'password' => bcrypt('jlH9M9MFUBu8'),
                'role' => 'doctor',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375295457277',
                'avatar' => 'myAvatar5.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Лиана',
                'last_name' => 'Воронина',
                'email' => 'VoroninaLiana271@gmail.com',
                'password' => bcrypt('9hxdxw5PKxKK'),
                'role' => 'doctor',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375292039015',
                'avatar' => 'myAvatar6.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Аваз',
                'last_name' => 'Соколов',
                'email' => 'SokolovAvaz48@gmail.com',
                'password' => bcrypt('irkCUVkNYrMX'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375295633162',
                'avatar' => 'myAvatar7.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Валентина',
                'last_name' => 'Макарова',
                'email' => 'MakarovaValentina281@gmail.com',
                'password' => bcrypt('37EryTfYUSF6'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375299247344',
                'avatar' => 'myAvatar8.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Эмма',
                'last_name' => 'Арджеванидзе',
                'email' => 'Ardjevanidze@gmail.com',
                'password' => bcrypt('veUhgjjYTAMD'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375299516502',
                'avatar' => 'myAvatar9.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Силантий',
                'last_name' => 'Недашковский',
                'email' => 'NedashkovskiySilantiy120@gmail.com',
                'password' => bcrypt('pbERi8fAN9BM'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375295448258',
                'avatar' => 'myAvatar10.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Кирилл',
                'last_name' => 'Ильин',
                'email' => 'IlinKirill351@gmail.com',
                'password' => bcrypt('WinMERivkQhT'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375299678420',
                'avatar' => 'myAvatar11.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Артемий',
                'last_name' => 'Амбарцумян',
                'email' => 'AmbartsumyanArtemiy386@gmail.com',
                'password' => bcrypt('L44aTUYvO9ue'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375293918501',
                'avatar' => 'myAvatar12.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ],
            [
                'first_name' => 'Филипп',
                'last_name' => 'Ильин',
                'email' => 'IlinFilipp373@gmail.com',
                'password' => bcrypt('cpvZfSa9IEDh'),
                'role' => 'patient',
                'birthday' => $this->rendDate(),
                'phone_number' => '+375299729434',
                'avatar' => 'myAvatar13.png',
                'created_at' => $this->rendDateTime(),
                'updated_at' => $this->rendDateTime(),
            ]
        ]);
    }
}
